version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  dataredis:
  django_media:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cineart_production_django
    volumes:
      - django_media:/app/cineart/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cineart_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cineart_production_traefik
    depends_on:
      - django
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - production_traefik:/etc/traefik/acme
      - django_media:/etc/traefik/media
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - dataredis:/data
    labels:
      traefik.enable: false
