# Generated by Django 3.0.7 on 2020-07-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144, verbose_name='Title')),
                ('description', models.TextField(max_length=800, verbose_name='Description')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('poster', models.FileField(upload_to='poster/', verbose_name='Poster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
