# Generated by Django 3.0.7 on 2020-07-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('fr', 'French')], max_length=2, verbose_name='Language')),
                ('text', models.FileField(upload_to='subtitles/', verbose_name='Text')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.Movie', verbose_name='Movie')),
            ],
        ),
    ]
